### ISSUE TITLE
AngelButtons still appear in HomeApp after rmoving them

### ISSUE THREAD

**Issue by Spy-1** [merdok/homebridge-xiaomi-fan#56] opened 2020-10-06 12:22 UTC
If you set the parameter "AngelButtons" and remove it at some point, the buttons will still be displayed in HomeApp. Even after a restart of Homebridge or Pi.

**Comment by merdok** [comment] 2020-10-06 12:44
You need to leave the property in but set an empty array as the value []. This should make them disappear.

**Comment by Spy-1** [comment] 2020-10-06 13:13
Thanks for your quick reply. I tried this but nothing changed.

**Comment by merdok** [comment] 2020-10-06 13:21
Hmm, should actually work. I will check that out and see if that is a bug.

**Comment by merdok** [comment] 2020-10-06 22:07
Should be fixed in version 1.4.3. I also updated the README to clarify that more! Please let me know if the issue is fixed!

**Comment by Trippersgarage** [comment] 2020-10-07 08:58
I've tested it with the empty array value and it works now. Nice.

**Comment by merdok** [comment] 2020-10-07 09:10
Good to hear. Then I think that this can be closed. Thanks!

**Closed as completed** 2020-10-07 09:10 UTC
